---
- name: Restart monitor services
  loop: "{{ monitor_services.results | selectattr('changed', 'equalto', true) | map(attribute='item') | map(attribute='service') | list }}"
  systemd:
    name: "{{ item }}"
    enabled: true
    state: restarted
    daemon-reload: true
