---
- name: Start Purdue rebuilderd daemon
  hosts:
    - seal.purdue.wtf
  become: true
  tags: [rebuilderd]
  roles:
    - purdue-rebuilderd

- name: Setup Purdue rebuilderd workers
  hosts:
    - seal.purdue.wtf
  become: true
  tags: [rebuilderd-worker]
  roles:
    - purdue-rebuilderd-worker

- name: Setup Purdue rebuilderd frontend
  hosts:
    - seal.purdue.wtf
  become: true
  tags: [rebuilderd-frontend]
  roles:
    - purdue-rebuilderd-frontend
