---
- name: Make sure required services are running
  systemd:
    state: started
    name: "{{ item }}"
  with_items:
    - docker
    - nginx-reverse
    - acme-companion

- name: Copy monitor service files
  copy:
    src: "{{ item.service }}"
    dest: /etc/systemd/system
    owner: core
    mode: 0644
  register: monitor_services
  notify:
    - Restart monitor services
  with_items:
    - { service: 'monitor-mirror.service' }
    - { service: 'monitor-grpc.service' }
    - { service: 'monitor-page.service' }

- name: Start monitor service
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
    daemon-reload: true
  with_items:
    - monitor-mirror.service
    - monitor-grpc.service
    - monitor-page.service
